#!/bin/bash

## Description: Run npm inside the web container in the root of the project (Use --prefix for another directory)
## Usage: npm [flags] [args]
## Example: "ddev npm install" or "ddev npm run deploy" or "ddev npm --prefix ./web/themes/front install"

ddev exec --raw bash -ic "npm $*"
ddev mutagen sync 2>/dev/null
