RUN arch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/) && \
    wget -O /tmp/wkhtmltox.deb "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_${arch}.deb"
# Install patched binary
# RUN apt --fix-broken install
RUN apt-get --assume-yes install xfonts-75dpi xfonts-base
RUN dpkg -i /tmp/wkhtmltox.deb
# Cleanup
RUN rm /tmp/wkhtmltox.deb
